### ISSUE TITLE
这个脚本会影响部分页面的加载

### ISSUE THREAD

**Issue by cooper1x** [Neulana/copy2clipboard#5]
比方说这个页面
https://kexuecat.github.io/2018/05/09/%E8%A7%A3%E5%86%B3Win10%E6%98%BE%E5%8D%A1%E5%86%B2%E7%AA%81%E5%AF%BC%E8%87%B4%E9%BC%A0%E6%A0%87%E5%8D%A1%E9%A1%BF/

打开报错是这个，文章内容显示不出来：
![image](https://user-images.githubusercontent.com/9080789/55211782-78c72f80-5228-11e9-8beb-a17fc13d3669.png)

脚本关闭后就好了，不知道是哪里冲突了。

**Comment by nickfan** [comment]
同上

https://ethendev.github.io/2018/12/17/JPA-MySQL-read-write-separation/

**Comment by pinple** [comment]
请升级到1.0，已修复
